LinuxCommand: update chmod, find, locate and which
BobAnkh/LinuxBeginner pull request #25
Opened 2020-07-12 08:38 UTC by Kelly510

- add basic function of linux command chmod
- add typical examples of linux command chmod
- plan to add info of linux command find, locate and which

2020-07-12 14:44 UTC, BobAnkh requested changes
请修改

2020-07-12 14:44 UTC, BobAnkh commented on docs/LinuxCommand/chmod.md
> +
注意事项与常用形式有重叠，建议归并

2020-07-13 01:56 UTC, Kelly510 commented
I’ve completed improvement of linux command head and tail, and also modified organization of chmod. Please review @BobAnkh .

2020-07-13 04:26 UTC, BobAnkh requested changes

2020-07-13 04:26 UTC, BobAnkh commented on docs/LinuxCommand/head.md
> +显示file.log文件的开头5行：
注意事项里给出了负数数字的说明，你可以把这个移到常用形式作为典型示例

2020-07-13 04:26 UTC, BobAnkh commented on docs/LinuxCommand/chmod.md
> +
此处有问题，u=x显然不是可读权限

2020-07-14 00:41 UTC, Kelly510 commented
I‘ve corrected the two errors. Please review. @BobAnkh

2020-07-14 02:52 UTC, BobAnkh approved these changes

2020-07-14 02:53 UTC, merged