docs(LinuxCommand): update more and less
BobAnkh/LinuxBeginner pull request #31
Opened 2020-07-18 14:25 UTC by Chengtian0730

- add basic functions of more and less
- add examples of more and less

ToDoList
- [ ] add basic functions and examples of more
- [ ] add basic functions and examples of less

2020-07-18 15:53 UTC, BobAnkh requested changes

2020-07-18 15:53 UTC, BobAnkh commented on docs/LinuxCommand/less.md
>  暂无
可以在注意事项中添加less与more相比的差异之处

more.md中的注意事项也可以自行斟酌，一并加以修改

2020-07-18 15:53 UTC, BobAnkh commented on docs/LinuxCommand/less.md
> +用于查看文件，除了像more命令一样可以向后翻看文件，也可以向前查看已浏览的文件，并且有向前或向后搜索字段。不同于more命令在查看时就加载整个文件，less命令并不会一开始就加载整个文件。
可以考虑单独将其功能提出来，将与more的比较放置到注意事项中

2020-07-20 07:41 UTC, Chengtian0730 commented
Already updated more and less. Please review. @BobAnkh

2020-07-20 07:42 UTC, BobAnkh approved these changes

2020-07-20 07:44 UTC, merged