docs(command):add linux command grep
BobAnkh/LinuxBeginner pull request #45
Opened 2020-08-06 13:51 UTC by nagi2330

## Description

a complete introduction to the command 'grep' is added to doc

- [x] add basic usage format of command grep
- [x] add arguments of command grep
- [x] add considerations of command grep
- [x] add typical examples of command grep
- [x] add descriptions of command grep

Resolves: #41 
## How Has This Been Tested?

grep.md has passed local mdl test according to .markdownlint.json as rules

## Types of changes

- Documentation (non-breaking change which updates documentation)

## Checklist:

- [x] Code follows the code style of this project.
- [x] Changes follow the **CONTRIBUTING** guidelines.
- [x] Update necessary documentation accordingly.
- [x] Lint and tests pass locally with the changes.
- [x] Check issues and pull requests first. You don't want to duplicate effort.

2020-08-06 14:07 UTC, nagi2330 commented
@BobAnkh I am curious what is wrong with my pr and commit mesage. gitmagic pointed that there is sth. wrong with the titles but i cannot find.  some help is needed! onegai~

2020-08-06 14:09 UTC, BobAnkh commented
You missed a space after `:` :joy:

2020-08-06 14:09 UTC, nagi2330 commented
got it! that is so tricky😂

2020-08-06 14:12 UTC, BobAnkh commented
Still facing space problem :joy:

Don’t underestimate this space, it’s an important detail to help us get style consistency

2020-08-07 01:53 UTC, nagi2330 commented
@BobAnkh  finished fixing typo and suggestion in yesterday's review has been adopted！

2020-08-07 02:13 UTC, BobAnkh requested changes
Great job! But still some things need to be changed

2020-08-07 02:13 UTC, BobAnkh commented on docs/LinuxCommand/grep.md
> +```bash
Change all `bash` to `console`

2020-08-07 02:13 UTC, BobAnkh commented on docs/LinuxCommand/grep.md
> +查找file.txt文件中所有含有'object'的行
Better to refactor this section.

Create a file and tell readers what's in it and show them the result of your command in the example

You can just creat one file but use it repeatedly in every example

2020-08-07 02:13 UTC, BobAnkh commented on docs/LinuxCommand/grep.md
> +grep -vc 'object' file.txt
Should give example of `grep -v` command

2020-08-07 02:16 UTC, nagi2330 commented
my fault，i push the wrong version again😂i will correct this very soon

2020-08-07 02:20 UTC, BobAnkh commented
To be honest, as a first-timer, you actually did much greater than others :smile: Keep on moving!

2020-08-07 02:48 UTC, BobAnkh commented
If you are ready for review and resolve the problem I proposed, please reply to the review and resolve conversation, then comment to me

2020-08-07 03:13 UTC, nagi2330 commented
> If you are ready for review and resolve the problem I proposed, please reply to the review and resolve conversation, then comment to me

I think it is time for reviewing! :D

2020-08-07 03:15 UTC, nagi2330 commented
I think it is time for reviewing! :D

> If you are ready for review and resolve the problem I proposed, please reply to the review and resolve conversation, then comment to me

I think it is time for another reviewing! :D

2020-08-07 03:17 UTC, BobAnkh commented
Ok I will review it and please next time reply to the reveiw before resolve it to make sure you don't resolve it unintentionally

2020-08-07 03:19 UTC, BobAnkh approved these changes
You are doing a great job!

I will merge it soon.

2020-08-07 03:20 UTC, nagi2330 commented
> Great job! But still some things need to be changed
replying to the review is doing something like this,is it?

2020-08-07 03:21 UTC, merged

2020-08-07 03:22 UTC, nagi2330 commented
> You are doing a great job!
> 
> I will merge it soon.

thanks! I will turn to investigating tool tree soon.

2020-08-07 03:23 UTC, BobAnkh commented
You should reply to that issue and then I will assign it to you